# Generated by Django 2.2 on 2020-11-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20201124_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-time'], 'verbose_name_plural': 'events'},
        ),
    ]
