# Generated by Django 2.2 on 2021-01-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20201203_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_online',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
