# Generated by Django 2.2 on 2021-01-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210112_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
