# Generated by Django 2.2 on 2021-01-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20210114_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
    ]
