# Generated by Django 2.2 on 2021-01-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20210114_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default-image.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='meet_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
