# Generated by Django 2.2 on 2021-02-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20210114_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
