# Generated by Django 2.2 on 2021-01-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_auto_20201213_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
