# Generated by Django 2.2 on 2021-01-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20210112_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='venue',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
